### ISSUE TITLE
API Documentation not available

### ISSUE THREAD

**Issue by ghost** [lumiacove/lumiastream-api-demo-js#2]
HI,

i tried to use the lumiastream api and in your examples you refrence the https://lumiastream.com/dev but this is not available.
Did you know the correct link to the documentation?

**Comment by ahadcove** [comment]
> HI,
> 
> i tried to use the lumiastream api and in your examples you refrence the https://lumiastream.com/dev but this is not available. Did you know the correct link to the documentation?

Wow, this is a very late reply but we fixed the redirect. This is the full url: https://dev.lumiastream.com/
